version: '3.8'

services:
  app_dev:
    container_name: warriv_dev
    build:
      context: .
      args:
        - BOT_ENV=development
    env_file:
      - .env.dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app_prod:
    container_name: warriv_prod
    build:
      context: .
      args:
        - BOT_ENV=production
    env_file:
      - .env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
