version: '3.8'

services:
  app:
    container_name: ${ENVIRONMENT}
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    env_file:
      - ${ENV_FILE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
