version: '3.8'

services:
  db:
    image: postgres
    container_name: dev_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - dev_pg_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    build: .
    container_name: dev_warriv
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  dev_pg_data: